# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# To check the syntax of this file: https://config.travis-ci.com/explore

language: r
dist: trusty # Build environment distribution
warnings_are_errors: true
os: windows # operating systems

deploy:
  provider: pages
  strategy: "git"
  cleanup: true
  keep_history: true
  token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: docs

cache:
  packages: true


r_packages:
  - covr
  - pkgdown
  - rgdal
  - devtools


after_success:
# Codecov
- Rscript -e 'covr::codecov(type ="all")'
# Help site folder
- mkdir docs
# Pull...
- git fetch origin gh-pages:gh-pages
# ...in docs
- git --work-tree=docs checkout gh-pages -- .
- travis_wait 60 Rscript -e 'pkgdown::build_site()'
# Empty file
- touch docs/.nojekyll
